name = "LeanAideTools"
defaultTargets = ["leanaidetools"]
testDriver="LeanAideToolsTest"

[[lean_lib]]
name = "LeanAideTools"

[[lean_exe]]
name = "leanaidetools"
root = "Main"

[[lean_lib]]
name = "LeanAideToolsTest"